apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog-service
          image: productcatelogregistry.azurecr.io/product-catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: uri

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: product-catalog