name: Node.js CI

on:
  push:
    branches: [ main ]  # Adjust branch name as needed
  pull_request:
    branches: [ main ]  # Adjust branch name as needed

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Adjust Node.js version as needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test